### ISSUE TITLE
Can you give Any Instructions?

### ISSUE THREAD

**Issue by RGZ1890** [deniro98/hackintosh-asus-zenbook-duo-ux482ea#11]
I only tried Ghost Image Restoration method, and i'm too  new to Opencore method.
I tried this efi method a month before, but I couldn't even boot into setup correctly.
is there any Step-by-step instructions to reference to, except Opencore official instructions?

If you want to, I can back some donation a bit. you can send me some E-mail for more contact.
thanks for checking up.

**Comment by ghost** [comment]
did you figure it out?

**Comment by RGZ1890** [comment]
> did you figure it out?

I just bought Macbook, since i couldn't figure out the things behind opencore.
